version: '3'

services:
  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - "5004:80"
    networks:
      - voteapp_net

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - "5003:80"
    networks:
      - voteapp_net

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - voteapp_net

  redis:
    image: redis:alpine
    networks:
      - voteapp_net

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    networks:
      - voteapp_net

  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - voteapp_net

networks:
  voteapp_net:
    driver: overlay
